[package]
name = "solrise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "=1.18.2"

[lib]
name = "solrise"
crate-type = ["cdylib", "lib"]